/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RadialGradientPaint;
import java.awt.RenderingHints;
import java.awt.geom.Point2D;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.plaf.PanelUI;
import javax.swing.plaf.TextUI;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.plaf.basic.BasicTableUI;
import javax.swing.plaf.basic.BasicTextFieldUI;

/**
 *
 * @author carlt
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    
    
        
    public frmPrincipal() {
        initComponents();
       //txtCadenas.setBackground(Color.white);

    }
    
        public static void cambiarColores(JPanel panel) {
	panel.setUI(new PanelUI() {
        @Override
        public void paint(Graphics g, JComponent c) {
            Graphics2D g2d = (Graphics2D) g;
            int width = c.getWidth();
            int height = c.getHeight();

           // GradientPaint gradient = new GradientPaint(0, 0, new Color(0, 0, 128), 0, height, new Color(0, 128, 255));
           
           
        Point2D center = new Point2D.Float(width / 2, height / 2);
        float radius = width / 2;
        float[] dist = {0.0f, 1.0f};
        Color[] colors = {new Color(0, 128, 255), new Color(0, 0, 128)};

        RadialGradientPaint paint = new RadialGradientPaint(center, radius, dist, colors);
        
        g2d.setPaint(paint);g2d.fillRect(0, 0, width, height);
            
            super.paint(g, c);
        }
    });
        }
        
    
     public static void cColorT(JTable tabla) {
	tabla.setUI(new BasicTableUI() {
        @Override
        public void paint(Graphics g, JComponent c) {
            Graphics2D g2d = (Graphics2D) g;
            int width = c.getWidth();
            int height = c.getHeight();

           // GradientPaint gradient = new GradientPaint(0, 0, new Color(0, 0, 128), 0, height, new Color(0, 128, 255));
           
           
        Point2D center = new Point2D.Float(width / 2, height / 2);
        float radius = width / 2;
        float[] dist = {0.0f, 1.0f};
        Color[] colors = {new Color(77, 166, 255), new Color(0, 128, 255)};

        RadialGradientPaint paint = new RadialGradientPaint(center, radius, dist, colors);
        
        g2d.setPaint(paint);g2d.fillRect(0, 0, width, height);
            
            super.paint(g, c);
            tabla.setForeground(Color.white);
        }
    });
        }
public static void cColor(JButton boton) {
	boton.setUI(new BasicButtonUI() {
        @Override
        public void paint(Graphics g, JComponent c) {
            Graphics2D g2d = (Graphics2D) g;
            int width = c.getWidth();
            int height = c.getHeight();
            
            Point2D center = new Point2D.Float(width / 2, height / 2);
        float radius = width / 2;
        float[] dist = {0.0f, 1.0f};
        Color[] colors = {new Color(77, 166, 255), new Color(0, 128, 255)};

        RadialGradientPaint paint = new RadialGradientPaint(center, radius, dist, colors);
            g2d.setPaint(paint);
            g2d.fillRect(0, 0, width, height);

            g2d.setColor(Color.WHITE); // Color del texto en blanco
            g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

            super.paint(g, c);
            boton.setForeground(Color.white);
        }
    });
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneles = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCadenas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnIngresar = new javax.swing.JButton();
        btnEvaluar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese una Cadena");

        txtCadenas.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCadenas.setSelectionColor(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Proyecto Final");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabla.setGridColor(new java.awt.Color(0, 0, 0));
        tabla.setOpaque(false);
        tabla.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tabla.setShowGrid(false);
        jScrollPane1.setViewportView(tabla);

        btnIngresar.setText("Ingresar Cadena");

        btnEvaluar.setText("Evaluar cadenas");

        btnLimpiar.setText("Limpiar");

        javax.swing.GroupLayout panelesLayout = new javax.swing.GroupLayout(paneles);
        paneles.setLayout(panelesLayout);
        panelesLayout.setHorizontalGroup(
            panelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelesLayout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(339, 339, 339))
            .addGroup(panelesLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEvaluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addGroup(panelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addComponent(txtCadenas))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelesLayout.setVerticalGroup(
            panelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(panelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCadenas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelesLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnEvaluar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEvaluar;
    public javax.swing.JButton btnIngresar;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel paneles;
    public javax.swing.JTable tabla;
    public javax.swing.JTextField txtCadenas;
    // End of variables declaration//GEN-END:variables


}
